MinimumStatiqDocsVersion-Docable: "1.0.0-beta.2"
SiteTitle: Documentation
ApiLayout: Api/_ApiLayout
FontLink: "https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;700&family=Roboto+Slab:wght@400;700&family=Roboto:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap"